sonar.projectKey=mahesh-newdevops_microservices-deployment
sonar.organization=mahesh-newdevops
sonar.projectName=microservices-deployment
sonar.sourceEncoding=UTF-8

sonar.sources=frontend,user-service,order-service,payment-service,notification-service,k8s
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.log
