apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: microservices

spec:
  replicas: 1

  selector:
    matchLabels:
      app: payment-service

  template:
    metadata:
      labels:
        app: payment-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"

    spec:
      containers:
      - name: payment-service
        image: payment-service:latest

        imagePullPolicy: Never

        env:
        - name: NODE_OPTIONS
          value: "--require @opentelemetry/auto-instrumentations-node/register"
        - name: OTEL_SERVICE_NAME
          value: payment-service
        - name: OTEL_TRACES_EXPORTER
          value: otlp
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_LOGS_EXPORTER
          value: none
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://alloy.monitoring.svc.cluster.local:4318/v1/traces

        ports:
        - containerPort: 3000
